name: Обновление подписки каждые 30 минут

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Скачать сервера и добавить название
        run: |
          curl -L -o servers.txt "https://sub.obbhod.online/premium"
          # Добавляем название подписки в закодированном виде
          echo "#profile-title: 8J+Tg01TQyBWUE7wn5O9" > subscription.txt
          echo "" >> subscription.txt
          cat servers.txt >> subscription.txt

      - name: Сохранить изменения
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add subscription.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Автообновление $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
